# Generated by Django 4.2.16 on 2026-03-14 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('title_prefix', models.CharField(default='A Full Stack', max_length=100)),
                ('title_option1', models.CharField(default='Developer', max_length=100)),
                ('title_option2', models.CharField(default='Engineer', max_length=100)),
                ('navbar_initials', models.CharField(default='RC', max_length=10)),
                ('about_text', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('education', models.CharField(default='', max_length=300)),
                ('copyright_year', models.CharField(default='2025', max_length=10)),
                ('copyright_name', models.CharField(default='', max_length=200)),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('resume_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatIDoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('tags', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatido_sections', to='portfolio.portfolioprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechStackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='techstack/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techstack_images', to='portfolio.portfolioprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('tools', models.CharField(max_length=500)),
                ('image', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('project_url', models.URLField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.portfolioprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_entries', to='portfolio.portfolioprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
