#!/usr/bin/env bash
# =============================================================================
# add-custom-domain.sh <domain>
#
# Automatically called by Django (via sudo) when a user saves a custom domain
# in the Admin Panel. Also works manually:
#   sudo bash deploy/add-custom-domain.sh johndoe.com
#
# What it does:
#   1. Validates the domain (strict regex — no shell metacharacters allowed)
#   2. Issues / renews a Let's Encrypt cert (webroot; falls back to standalone)
#   3. Writes an nginx server block to sites-available
#   4. Enables it and reloads nginx
#
# One-time setup (do this ONCE as root before it can be called automatically):
#   sudo visudo -f /etc/sudoers.d/portfolio-deploy
#   # Add this line:
#   quickrpe ALL=(root) NOPASSWD: /home/quickrpe/portfolio/deploy/add-custom-domain.sh
#   sudo chmod 0440 /etc/sudoers.d/portfolio-deploy
#   sudo chmod +x /home/quickrpe/portfolio/deploy/add-custom-domain.sh
# =============================================================================

set -euo pipefail

# ─── Config ───────────────────────────────────────────────────────────────────
DEPLOY_DIR="/home/quickrpe/portfolio"
SITE_DOMAIN="portfolio.dotdevz.com"        # Host header passed to Django
EMAIL="${SSL_EMAIL:-admin@dotdevz.com}"

# ─── Input validation ─────────────────────────────────────────────────────────
DOMAIN="${1:-}"

# Strict RFC-compliant hostname regex — rejects any shell special characters.
# Allows: letters, digits, hyphens, dots. Min 2 labels. No leading/trailing dots or hyphens.
if [[ -z "${DOMAIN}" ]]; then
    echo "[ERROR] Usage: $0 <domain>" >&2
    exit 1
fi

# Validate with grep POSIX ERE (no -P needed for basic safety check)
if ! echo "${DOMAIN}" | grep -qE '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$'; then
    echo "[ERROR] Invalid domain name '${DOMAIN}' — rejected for safety." >&2
    exit 1
fi

# Block attempts to use our own platform domain as a custom domain
if echo "${DOMAIN}" | grep -qE "(^|\.)portfolio\.dotdevz\.com$"; then
    echo "[ERROR] Cannot use platform domain as custom domain." >&2
    exit 1
fi

echo "[INFO] Processing custom domain: ${DOMAIN}"

CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"
NGINX_CONF="/etc/nginx/sites-available/portfolio-custom-${DOMAIN}"
NGINX_LINK="/etc/nginx/sites-enabled/portfolio-custom-${DOMAIN}"
WEBROOT="${DEPLOY_DIR}"

# ─── TLS certificate ──────────────────────────────────────────────────────────
if [[ -f "${CERT_DIR}/fullchain.pem" ]]; then
    echo "[INFO] Certificate already exists for ${DOMAIN}, skipping certbot."
else
    echo "[INFO] Requesting Let's Encrypt certificate for ${DOMAIN}..."

    # Try webroot first (nginx keeps running, certbot serves challenge file)
    if certbot certonly \
        --webroot -w "${WEBROOT}" \
        --non-interactive --agree-tos \
        --email "${EMAIL}" \
        --expand \
        -d "${DOMAIN}" 2>&1; then
        echo "[INFO] Certificate issued via webroot."
    else
        echo "[WARN] Webroot challenge failed. Stopping nginx for standalone mode..."
        systemctl stop nginx
        certbot certonly \
            --standalone \
            --non-interactive --agree-tos \
            --email "${EMAIL}" \
            --expand \
            -d "${DOMAIN}"
        systemctl start nginx
        echo "[INFO] Certificate issued via standalone."
    fi
fi

# ─── Nginx server block ───────────────────────────────────────────────────────
echo "[INFO] Writing nginx config: ${NGINX_CONF}"

cat > "${NGINX_CONF}" <<NGINXBLOCK
# Auto-generated by add-custom-domain.sh on $(date -u)
# Custom domain for portfolio user.
server {
    listen 80;
    server_name ${DOMAIN};

    # Let's Encrypt HTTP-01 renewal path
    location ~ ^/.well-known {
        root ${DEPLOY_DIR};
        allow all;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root  ${DEPLOY_DIR}/dist;
    index index.html;
    client_max_body_size 20M;

    location = /favicon.ico { access_log off; log_not_found off; }

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location /api/ {
        include proxy_params;
        proxy_pass http://unix:${DEPLOY_DIR}/portfolio.sock;
        # Rewrite Host so Django ALLOWED_HOSTS accepts it.
        # X-Custom-Domain carries the real domain for profile lookup.
        proxy_set_header Host            ${SITE_DOMAIN};
        proxy_set_header X-Custom-Domain ${DOMAIN};
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }

    location /static/ { alias ${DEPLOY_DIR}/backend/staticfiles/; }
    location /media/  { alias ${DEPLOY_DIR}/backend/media/; }

    add_header X-Frame-Options        "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff"    always;
}
NGINXBLOCK

# ─── Enable site ──────────────────────────────────────────────────────────────
if [[ ! -L "${NGINX_LINK}" ]]; then
    ln -s "${NGINX_CONF}" "${NGINX_LINK}"
    echo "[INFO] Site enabled: ${NGINX_LINK}"
else
    echo "[INFO] Site already enabled, config updated."
fi

# ─── Test + reload ────────────────────────────────────────────────────────────
echo "[INFO] Testing nginx config..."
nginx -t

echo "[INFO] Reloading nginx..."
systemctl reload nginx

echo "[OK] Custom domain '${DOMAIN}' is now active with HTTPS."
